---
kind: pipeline
type: kubernetes
name: build

trigger:
  event:
    - push

steps:
  - name: build project
    image: quay.io/ukhomeofficedigital/openjdk11:v11.0.11_9-2
    commands:
      - ./gradlew assemble --no-daemon

  - name: test project
    image: quay.io/ukhomeofficedigital/openjdk11:v11.0.11_9-2
    commands:
      - ./gradlew check --no-daemon
    depends_on:
      - build project

  - name: build & push
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/ukhomeofficedigital/hocs-bulk-case-action
      tags:
        - ${DRONE_COMMIT_SHA}
    environment:
      DOCKER_PASSWORD:
        from_secret: QUAY_ROBOT_TOKEN
      DOCKER_USERNAME: ukhomeofficedigital+hocs_quay_robot
    depends_on:
      - test project

---
kind: pipeline
type: kubernetes
name: deploy
depends_on:
  - build

steps:
  - name: deploy to not prod
    image: quay.io/ukhomeofficedigital/kd:v1.19.13
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: ${DRONE_DEPLOY_TO}
      KUBE_TOKEN:
        from_secret: hocs_bulk_case_action_${DRONE_DEPLOY_TO/-/_}
      KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      CLUSTER_NAME: acp-notprod
    when:
      event:
        - promote
      target:
        exclude:
          - "*-prod"

  - name: deploy to prod
    image: quay.io/ukhomeofficedigital/kd:v1.19.13
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: ${DRONE_DEPLOY_TO}
      KUBE_TOKEN:
        from_secret: hocs_bulk_case_action_${DRONE_DEPLOY_TO/-/_}
      KUBE_SERVER: https://kube-api-prod.prod.acp.homeoffice.gov.uk
      CLUSTER_NAME: acp-prod
    when:
      event:
        - promote
      target:
        include:
          - "*-prod"
